---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-jellyfin-smb
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: pv-jellyfin-smb
  storageClassName: smb